### ISSUE TITLE
Check "entity" format in released datasets

### ISSUE THREAD

**Issue by robertoturrin** [crowdrec/datasets#4]
Entities should follow the "5 tab-separated columns format" (see [https://github.com/crowdrec/idomaar/wiki/DATA-FORMAT]) where the columns are:
* entity type
* entity id
* timestamp
* properties (json)
* linked entities (json)

Please check (for instance [https://github.com/crowdrec/datasets/blob/master/01.MovieTweetings/datasets/snapshots_10K/evaluation/training/entities.dat]) the datasets as entities are formatted as *3* tab-separated columns data

**Comment by robertoturrin** [comment]
A correct example of data is: [https://github.com/crowdrec/datasets/blob/master/01.MovieTweetings/datasets/snapshots_10K/entities.dat]

(However, the idomaar-demo script seems to use the incorrect one)

**Comment by davidemalagoli** [comment]
the demo script use the data at: 
https://github.com/crowdrec/datasets/blob/master/01.MovieTweetings/datasets/snapshots_10K/evaluation/test/data.dat

and it seams to me that is in the correct format, which is the error?
